import time
import sys

def generateRestPoint(gridspace,gridlist,pointlist):
    restgids=[]
    xyz=gridspace.shape
    gridnum=0
    grids=xyz[0]*xyz[1]*xyz[2]
    for x in range(xyz[0]):
        for y in range(xyz[1]):
            for z in range(xyz[2]):
                if gridspace[x][y][z]!=-1:
                    restgids.append(gridspace[x][y][z])
                gridnum+=1
                if gridnum%(grids//100)==0:
                    print(time.asctime( time.localtime(time.time()))+"  Log:  已生成"+str(gridnum//(grids//100))+"%新栅格")
    
    restpids=[]
    pointnum=0
    for gid in restgids:
        for pid in gridlist[gid].pointList:
            restpids.append(pid)
        pointnum+=1
        if pointnum%(len(restgids)//100)==0:
            print(time.asctime( time.localtime(time.time()))+"  Log:  已生成"+str(pointnum//(len(restgids)//100))+"%新点")

    restpointlist=[]
    linenum=0
    for pid in restpids:
        restpointlist.append(pointlist[pid])
        linenum+=1
        if linenum%(len(restpids)//100)==0:
            print(time.asctime( time.localtime(time.time()))+"  Log:  已生成"+str(linenum//(len(restpids)//100))+"%新行")
    return restpointlist

'''
def generateRestCloud(head,restpoints,restname):
    profile=open(file='profile.txt',mode='r',encoding='utf-8')
    lines=profile.readlines()
    profile.close()
    cloudname=lines[1][:-5]                                            #点云文件名称
    file2=open((cloudname+'→'+restname+'.ply'),'w+',encoding="utf-8")
    l=0
    for line in range(len(head)):
        if head[line][0]=='e' and head[line][1]=='l':
            l=line
    head[l]='element vertex '+str(len(restpoints))+'\n'
    file2.writelines(head)
    file2.writelines(restpoints)
    file2.close()
'''

def generateNewCloud(newpointlist,newname):
    #profile=open(file='profile.txt',mode='r',encoding='utf-8')
    #lines=profile.readlines()
    #profile.close()
    #cloudname=lines[1][:-5]                                            #点云文件名称
    cloudname=str(sys.argv[1][:-4])                                            #点云文件名称
    file2=open((cloudname+'→'+newname+'.ply'),'w+',encoding="utf-8")
    head="ply\nformat ascii 1.0\ncomment Created by wanahoran\ncomment Created "+time.asctime( time.localtime(time.time()))+"\nobj_info Generated by wanhaoran!\nelement vertex "+str(len(newpointlist))+"\nproperty float x\nproperty float y\nproperty float z\nproperty uchar red\nproperty uchar green\nproperty uchar blue\nend_header\n"
    newpoints=[]
    linenum=0
    for point in newpointlist:
        xyz=point.getXyz()
        rgb=point.getRgb()
        strP=str(xyz[0])+' '+str(xyz[1])+' '+str(xyz[2])+' '+str(rgb[0])+' '+str(rgb[1])+' '+str(rgb[2])+' '+'\n'
        newpoints.append(strP)
        linenum+=1
        if linenum%(len(newpointlist)//100)==0:
            print(time.asctime( time.localtime(time.time()))+"  Log:  正在写入文件"+str(linenum//(len(newpointlist)//100))+"%")
    file2.write(head)
    file2.writelines(newpoints)
    file2.close()